### ISSUE TITLE
Integers in Dicts are not preserved

### ISSUE THREAD

**Issue by stratosgear** [stephenmcd/hot-redis#10]
Adding the following test case, the tests fail.

    class DictTests(BaseTestCase):
    
        def test_integer(self):
            a = {"wagwaan": 5, "flute": "don"}
            self.assertEqual(hot_redis.Dict(a), a)

with:

    python tests.py
    ...................F.....................................................................................
    ======================================================================
    FAIL: test_integer (__main__.DictTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "tests.py", line 397, in test_integer
        self.assertEqual(hot_redis.Dict(a), a)
    AssertionError: Dict({u'wagwaan': u'5', u'flute': u'don'}, '5f74dc31-1bbb-4304-8ce8-a80a6337514a') != {'wagwaan': 5, 'flute': 'don'}

    ----------------------------------------------------------------------
    Ran 105 tests in 4.337s
    
    FAILED (failures=1)

Any idea why the 'wagwaan' int is transformed to a string?

**Comment by stephenmcd** [comment]
That's how Redis works, it only stores strings as values. If you know you're putting ints in, you should cast them when you get them back out.

**Comment by stephenmcd** [comment]
```
$ redis-cli hmset myhash a 1 b 2
OK

$ redis-cli hgetall myhash
1) "a"
2) "1"
3) "b"
4) "2"```
