### ISSUE TITLE
List type is broken

### ISSUE THREAD

**Issue by tcatut** [stephenmcd/hot-redis#12]
If it's important, the below behavior was seen under Python 3.4.

It's not possible to overwrite your List object once it's created.  In normal Python list type, if you set a list equal to a new list then it will just overwrite the existing list.  However, in your List type if you try to overwrite the value it will call extend every time.

I even tried closing my application and re-starting.  Since the object in Redis is actually still storing the old value, the problem persists even through application restart.  This is especially fun when you use the "initial" parameter on startup.  You basically end up with a list that gets extended over and over again every time the application restarts.

Also, you should respect the types of objects passed inside the list itself.  In my example below, I'm passing INT types inside my list; but your library gives the list items back as STRING types.  In normal python lists, if the list contains INT you get back INT.

PYTHON EXAMPLE:
```
>>> pythonList = [1,2,3]
>>> print(pythonList)
[1, 2, 3]
>>> pythonList = [4,5,6]
>>> print(pythonList)
[4, 5, 6]
```

HOT_REDIS EXAMPLE:
```
>>> from hot_redis import List
>>> theList = List(key='abc', initial=[1,2,3])
>>> print(theList)
List(['1', '2', '3'], 'abc')
>>> print(theList.value)
['1', '2', '3']
>>> theList = List(key='abc', initial=[4,5,6])
>>> print(theList)
List(['1', '2', '3', '4', '5', '6'], 'abc')
>>> print(theList.value)
['1', '2', '3', '4', '5', '6']
>>> theList.value = [1,2,3]
>>> print(theList)
List(['1', '2', '3', '4', '5', '6', '1', '2', '3'], 'abc')
>>> print(theList.value)
['1', '2', '3', '4', '5', '6', '1', '2', '3']
```

**Comment by tcatut** [comment]
I get that Redis stores things as strings.  However, isn't the whole point of your library to make Redis objects behave like Python objects again?  In my opinion this means that you should respect the types set originally.  If the item you're getting back out looks like an INT, etc. then you should be converting automatically.

This problem is even worse if you try to do something like a nested list.  You don't respect the type coming back out; so the nested items come back as a string that has to go through separate translation.  Maybe this is OK, but maybe you could also do something like create additional Redis objects automatically for nested Lists, Dicts, etc?

**Comment by bastianh** [comment]
The libraries purpose is to have a python object like interface to redis methods and datatypes, not the other way around.

There is no function in redis to replace a list.. because that does not really make sense. Redis lists work like queues.. one worker puts somthing in it, others take something out.
