### ISSUE TITLE
After modifying data, the data is not updated in a timely manner！

### ISSUE THREAD

**Issue by 8hours** [stephenmcd/hot-redis#9]
![image](https://cloud.githubusercontent.com/assets/6057587/12741978/7250b3e4-c9bc-11e5-842b-e93eb992e79b.png)
Hello, I met such a problem, I want to the inside of the django data import to redis, my code is as follows

![image](https://cloud.githubusercontent.com/assets/6057587/12742001/a02922b0-c9bc-11e5-823f-6449a775750b.png)

**Comment by stephenmcd** [comment]
I'm very sorry, this makes no sense.
